name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Acessar painel da PET 6
        run: |
          curl -L --max-time 60 --retry 3 --retry-delay 10 "https://coleta-dados-pet6.streamlit.app/" || true